'use client';
import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useState } from 'react';
import { story } from '@/data/story';
import { OptionalImage } from './OptionalImage';

type InstagramScreenshotProps = { src?: string };
function Placeholder(){return <div className="grid aspect-[9/16] w-full place-items-center rounded-[1.4rem] bg-[#efe3cf] px-8 text-center text-espresso"><div><p className="font-serif text-2xl">Our first Instagram conversation</p><p className="mt-3 text-xs uppercase tracking-[.24em] text-gold">{story.beginning.placeholder}</p></div></div>}
export function InstagramScreenshot({src}:InstagramScreenshotProps){const[expanded,setExpanded]=useState(false);useEffect(()=>{function onKey(e:KeyboardEvent){if(e.key==='Escape')setExpanded(false)}; if(expanded) window.addEventListener('keydown',onKey); return()=>window.removeEventListener('keydown',onKey)},[expanded]);return <><button onClick={()=>setExpanded(true)} className="relative mx-auto block w-full max-w-[22rem] rounded-[2rem] border border-gold/30 bg-espresso p-3 shadow-[0_30px_80px_rgba(27,18,14,.20)]" aria-label="Open readable first Instagram message"><span className="absolute -right-8 top-8 rotate-6 font-serif text-xl italic text-rose">{story.beginning.annotation}</span><span className="absolute -left-6 top-16 rounded-full bg-ivory/90 px-3 py-2 text-[.65rem] uppercase tracking-[.2em] text-gold shadow">{story.beginning.floatingDate}</span><OptionalImage src={src} alt="First Instagram conversation" className="aspect-[9/16] rounded-[1.45rem]" imageClassName="object-contain bg-[#efe3cf]" fallback={<Placeholder/>}/></button><AnimatePresence>{expanded?<motion.div role="dialog" aria-modal="true" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[80] grid place-items-center bg-espresso/95 p-4 backdrop-blur"><button onClick={()=>setExpanded(false)} className="absolute right-4 top-4 rounded-full border border-gold/50 px-4 py-2 text-sm text-gold" aria-label="Close Instagram screenshot lightbox">Close</button><OptionalImage src={src} alt="Expanded first Instagram conversation" className="h-[86dvh] w-full max-w-2xl" imageClassName="object-contain" fallback={<div className="w-full max-w-sm"><Placeholder/></div>}/></motion.div>:null}</AnimatePresence></>}
